name: build and release using pyoxidizer
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:  # trigger from ui

env:
  PYOXIDIZER_PROFILE: release
  CLI_NAME: peek
  ENTRY_POINT: peek.py

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyOxidizer
        run: cargo install pyoxidizer

      - name: Install Pillow
        run: pip install Pillow

      - name: Build with PyOxidizer
        run: pyoxidizer build --release

      - name: Install FPM & package .deb
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm
          BIN=build/${{ env.PYOXIDIZER_PROFILE }}/bin/${{ env.CLI_NAME }}
          chmod +x "$BIN"
          tar czf peek-linux.tar.gz -C "$(dirname $BIN)" "$(basename $BIN)"
          fpm -s dir \
              -t deb \
              -n ${{ env.CLI_NAME }} \
              -v "${{ github.ref_name }}" \
              --prefix /usr/local/bin \
              "$BIN"

      - name: Package Windows EXE
        if: matrix.os == 'windows-latest'
        run: |
          BIN=build\\${{ env.PYOXIDIZER_PROFILE }}\\bin\\${{ env.CLI_NAME }}.exe
          powershell -Command "Compress-Archive -Path $env:BIN -DestinationPath peek-windows.zip"

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            peek-linux.tar.gz
            peek-windows.zip
            peek_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
